#pragma once

// From glfw3.h
#define MYKA_MOUSE_BUTTON_1         0
#define MYKA_MOUSE_BUTTON_2         1
#define MYKA_MOUSE_BUTTON_3         2
#define MYKA_MOUSE_BUTTON_4         3
#define MYKA_MOUSE_BUTTON_5         4
#define MYKA_MOUSE_BUTTON_6         5
#define MYKA_MOUSE_BUTTON_7         6
#define MYKA_MOUSE_BUTTON_8         7
#define MYKA_MOUSE_BUTTON_LAST      MYKA_MOUSE_BUTTON_8
#define MYKA_MOUSE_BUTTON_LEFT      MYKA_MOUSE_BUTTON_1
#define MYKA_MOUSE_BUTTON_RIGHT     MYKA_MOUSE_BUTTON_2
#define MYKA_MOUSE_BUTTON_MIDDLE    MYKA_MOUSE_BUTTON_3
